pipeline {
    agent any
    tools {
        maven 'Maven 3.6.1' 
    }
    stages {
        stage('build') {
            steps {
                echo 'Compiling app..'
                dir('web-quarantine') {
                    sh 'mvn compile'
                }
            }
        }
        stage('test') {
            steps {
                echo 'Running unit tests..'
                dir('web-quarantine') {
                    sh 'mvn clean test'
                }
            }
        }
       stage('package') {
            steps {
                echo 'Packing app..'
                dir('web-quarantine') {
                    sh 'mvn package -DskipTests'
                    archiveArtifacts artifacts: 'target/*.jar', fingerprint:true
                }
            }
        }
    }

    post {
      always {
        echo 'Building multibranch pipeline for users is completed..'
      }
   }
}
