pipeline {
    agent none

    stages {
        stage('build') {
            agent {
              docker {
                image 'maven:3.6.1-jdk-8-slim'
                args '-v $HOME/.m2:/root/.m2'
              }
            }

            steps {
                echo 'Compiling users app..'
                dir('web-quarantine') {
                    sh 'mvn compile'
                }
            }
        }
        stage('test') {
            agent {
              docker {
                image 'maven:3.6.1-jdk-8-slim'
                args '-v $HOME/.m2:/root/.m2'
              }
            }
            steps {
                echo 'Running unit tests on uers app..'
                dir('web-quarantine') {
                    sh 'mvn clean test'
                }
            }
        }
       stage('package') {
            agent {
              docker {
                image 'maven:3.6.1-jdk-8-slim'
                args '-v $HOME/.m2:/root/.m2'
              }
            }
            steps {
                echo 'Packing users app..'
                dir('web-quarantine') {
                    sh 'mvn package -DskipTests'
                    archiveArtifacts artifacts: 'target/*.jar', fingerprint:true
                }
            }
        }
     }

    post {
      always {
        echo 'Building multibranch pipeline for users is completed..'
      }
   }
}
